INSERT INTO PRODUCT (
  ID,
  OBJECT,
  ACTIVE,
  CREATED,
  DEFAULT_PRICE,
  DESCRIPTION,
  LIVEMODE,
  NAME,
  SHIPPABLE,
  STATEMENT_DESCRIPTOR,
  TAX_CODE,
  UNIT_LABEL,
  UPDATED,
  URL,
  SKU,
  TITLE,
  LINK_TO_GENERIC_PHOTO_FILE,
  AVAILABLE_SIZES,
  CURRENCY_FORMAT,
  IS_FREE_SHIPPING,
  PRICE,
  STYLE,
  INSTALLMENTS,
  USER_ID
) VALUES
(1, 'pltv', FALSE, 98311, 17.0, 'Plateau en verre réchauffe plat, forme ellyptique', FALSE, 'Computer c deposit', FALSE, 'withdrawal THX b', 'Metal', 'infomediaries partnerships b', 91058, 'https://lionel.fr', 'pltv', 'Plateau en verre réchauffe plat', '../../../content/productsImages/18C0776C-D2A4-4E57-B3DE-AE1E13FABB42-bis.jpg', '12 cm x 24 cm', 'euros', FALSE, 17.0, 'ellyptique', 1, 2),
(2, 'btts', FALSE, 40746, 238.0, 'Bottes en cuir , noirs, demi longueur', FALSE, 'Manager', FALSE, 'de', 'Intelligent', 'pixel methodical quantifying', 78950, 'http://vivien.net', 'btts', 'Bottes cuir', '../../../content/productsImages/b091f7d115bf473cb7934c78d5053e7a.webp', 'toutes pointures', 'euros', FALSE, 238.0, 'demi longueur', 2, 2),
(3, 'bllndf', FALSE, 51756, 324.5, 'Ballon de foot pro, noir et blanc', FALSE, 'Dinar', TRUE, 'transmit Incredible IB', 'Algérie Rustic', 'Taka', 90493, 'http://josse.net', 'bllndf', 'Ballon de foot', '../../../content/productsImages/1268707_big.webp', 'usuel', 'euros', FALSE, 324.5, 'Noir & blanc', 1, 1),
(4, 'jtsk', TRUE, 94512, 12730.0, 'Jet-Ski MT 245  cv vert et bleu', TRUE, 'Soft', TRUE, 'pink Sausages', 'Computers Jamaïque', 'Electronics', 20046, 'http://thierry.fr', 'jtsk', 'Jet-Ski', '../../../content/productsImages/22MY_ULTRA_310X_BK1_STU__2_.png', 'usual', 'euros', FALSE, 12730.0, 'vert et bleu', 5, 1),
(5, 'lnt', FALSE, 91355, 325.0, 'Lunette plexi glass grands verres, légères', TRUE, 'mint', TRUE, 'exuding copying', 'services a', 'transmitting Account', 18057, 'https://colin.info', 'lnt', 'Lunette plexi glass', '../../../content/productsImages/lunettes-ekoi-persoevo8-noir-mirror-cat3.webp', 'wireless Practical a', 'euros', TRUE, 325.0, NULL, 1, 2),
(6, 'qrl', FALSE, 20850, 119154.0, 'Aquarelle: la femme au buste dénudé de Jean Monnet', TRUE, 'Producteur', TRUE, 'teal Vision-oriented', 'Ergonomic Bedfordshire', 'ADP payment maximize', 16931, 'https://brunehaut.eu', 'qrl', 'Aquarelle buste dénudé', '../../../content/productsImages/383842_poster_m.jpg', 'global', 'euros', TRUE, 119154.0, 'impressionnisme', 3, 1),
(7, 'gtr', FALSE, 84403, 250.0, 'guitare classique , façade jaune, flanc verni', TRUE, 'mobile', FALSE, 'Incredible', 'navigate', 'invoice a sticky', 49383, 'https://landry.info', 'gtr', 'guitare classique', '../../../content/productsImages/81tQhEEtiEL._AC_SX679_.jpg', 'usuel', 'euros', TRUE, 250.0, 'classique', 2, 2),
(8, 'scdlx', TRUE, 86844, 735.0, 'Sac de luxe , marque Louis Vuitton (vrai) contrôlé sans contre façon', FALSE, 'Clothing', TRUE, 'Uganda primary Ergonomic', 'Games copying', 'Costa c du', 85943, 'https://roland.fr', 'scdlx', 'Sac de luxe', '../../../content/productsImages/louis-vuitton-cabas-onthego-gm-toile-monogram-sacs-à-main--M45320_PM2_Front view.webp', 'moyen', 'euros', FALSE, 735.0, 'Marron', 3, 1),
(9, 'mnjp', FALSE, 54388, 65.0, 'Mini jupe sexy, couleur gris clair métallisé, taille dentellé', TRUE, 'Macédoine transmit', TRUE, 'Account Adolphe', 'Unbranded', 'adapter Auto neural', 54441, 'https://amarande.fr', 'mnjp', 'Mini jupe', '../../../content/productsImages/Mini-jupe-d-coli-re-pliss-e-en-dentelle-douce-pour-femmes-cosplay-court-mini-robe.jpg', 'toutes tailles', 'euros', TRUE, 65.0, 'ultra court', 2, 1),
(10, 'rbdm', TRUE, 30207, 955.0, 'Robe de mariage style baroque, couleur rose satiné', FALSE, 'Berkshire IB Card', FALSE, 'Champagne-Ardenne Saint-Honoré', 'c Cross-platform partnerships', 'bi-directional Limousin', 85148, 'https://acace.eu', 'rbdm', 'Robe de mariage', '../../../content/productsImages/i.imgur.com_AKVFra1.jpeg', 'M, XL', 'euros', FALSE, 955.0, 'baroque', 5, 2),
(1001, 'tdsgz', FALSE, 98311, 985.0, 'Tondeuse à gazon Moteur 5 cv / 5 vitesses', FALSE, 'Computer c deposit', FALSE, 'withdrawal THX b', 'Metal', 'infomediaries partnerships b', 91058, 'https://lionel.fr', 'tdsgz', 'Tondeuse à gazon', '../../../content/productsImages/51269-tondeuse-18v-ryobi-2.jpg', 'Computer CFP orange', 'euros', FALSE, 985.0, 'vert', 3, 2),
(1002, 'vllmdrn', TRUE, 40746, 2575000.0, 'Villa moderne, avec piscine et sous-sol garage/grenier, 12 pièces totales garage compris', FALSE, 'Manager', FALSE, 'de', 'Intelligent', 'pixel methodical quantifying', 78950, 'http://vivien.net', 'vllmdrn', 'Villa moderne', '../../../content/productsImages/0ekucocxabry71r1voy73fz78hl3kvx9n434voz9c.jpg', 'AGP lavender', 'euros', TRUE, 2575000.0, 'Moderne', 90, 1),
(1003, 'nkhpdtf', FALSE, 51756, 25.1, 'Ankh pendentif format : 3.14 cm x 6.28 cm, en argent inoxydable', FALSE, 'Dinar', TRUE, 'transmit Incredible IB', 'Algérie Rustic', 'Taka', 90493, 'http://josse.net', 'nkhpdtf', 'Ankh pendentif', '../../../content/productsImages/61biD6whgEL._AC_UY625_.jpg', '3.14 cm x 6.28 cm', 'euros', FALSE, 25.1, 'Antique', 1, 3),
(1004, 'cptrpcl', TRUE, 94512, 57.0, 'Pork pie, Chapeau tropical, en paille rigide', TRUE, 'Soft', TRUE, 'pink Sausages', 'Computers Jamaïque', 'Electronics', 20046, 'http://thierry.fr', 'cptrpcl', 'Chapeau tropical', '../../../content/productsImages/Lambert-porkpie-hat-khaki.webp', 'toutes tailles', 'euros', FALSE, 57.0, 'tropical', 2, 2),
(1005, 'sctrymh', FALSE, 91355, 625.0, 'Scooter Yamaha, 50 cm3, 75 00 km, couleur gris et bleu clair métallisé', TRUE, 'mint', TRUE, 'exuding copying', 'services a', 'transmitting Account', 18057, 'https://colin.info', 'sctrymh', 'Scooter 50 cm3', '../../../content/productsImages/productsImagesi.imgur.com_LFe1TYX.jpeg', '50 cm3', 'euros', TRUE, 625.0, '50 cm3', 5, 1);
-- RUNSCRIPT FROM 'C:\Users\rafar\IdeaProjects\Madaskill\src\main\resources\config\liquibase\h2-db-madaskill-jhipster.sql'
